name: marcopolo
description: "Persian offline country quiz game (flag / currency / capital)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  audioplayers: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/icon/ic_legacy.png"
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/ic_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/ic_legacy.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/data/countries.json
    - assets/flags/4x3/
    - assets/maps/
    - assets/sounds/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-VF.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
